FROM python:3.9-slim

WORKDIR /app

RUN pip3 install web.py

COPY server.py /app

#change the ip after --kong_url to ip of kong gateway without port
CMD ["python", "server.py", "0.0.0.0:8080", "--kong_url", "127.0.0.1"] 